// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/domain/events"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/domain/repositories"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/domain/storage"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/infra/cache"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/infra/http/handlers"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/infra/kafka"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/infra/persistence"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/infra/s3storage"
	"github.com/DiegoJCordeiro/image-resizing-go-producer-api/internal/usecases"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

// Handlers
func NewImageHandler(getImageUseCase usecases.GetImageUseCase, insertImageUseCase usecases.InsertImageUseCase, deleteImageUseCase usecases.DeleteImageUseCase) *handlers.ImageHandler {
	imageHandler := handlers.NewImageHandler(getImageUseCase, insertImageUseCase, deleteImageUseCase)
	return imageHandler
}

// UseCases
func NewGetImageUseCase(database *mongo.Database, redisClient *redis.Client) usecases.GetImageUseCase {
	imageMongoDBRepositoryImpl := persistence.NewImageMongoDBRepositoryImpl(database)
	imageRedisBRepositoryImpl := cache.NewImageRedisBRepositoryImpl(redisClient)
	s3StorageImpl := s3storage.NewS3StorageImpl()
	getImageUseCase := usecases.NewGetImageUseCase(imageMongoDBRepositoryImpl, imageRedisBRepositoryImpl, s3StorageImpl)
	return getImageUseCase
}

func NewInsertImageUseCase(kafkaProducer events.EventProducer, database *mongo.Database, redisClient *redis.Client) usecases.InsertImageUseCase {
	imageMongoDBRepositoryImpl := persistence.NewImageMongoDBRepositoryImpl(database)
	imageRedisBRepositoryImpl := cache.NewImageRedisBRepositoryImpl(redisClient)
	s3StorageImpl := s3storage.NewS3StorageImpl()
	insertImageUseCase := usecases.NewInsertImageUseCase(kafkaProducer, imageMongoDBRepositoryImpl, imageRedisBRepositoryImpl, s3StorageImpl)
	return insertImageUseCase
}

func NewDeleteImageUseCase(database *mongo.Database, redisClient *redis.Client) usecases.DeleteImageUseCase {
	imageRedisBRepositoryImpl := cache.NewImageRedisBRepositoryImpl(redisClient)
	imageMongoDBRepositoryImpl := persistence.NewImageMongoDBRepositoryImpl(database)
	deleteImageUseCase := usecases.NewDeleteImageUseCase(imageRedisBRepositoryImpl, imageMongoDBRepositoryImpl)
	return deleteImageUseCase
}

// Producers
func NewImageProducerImpl(bootstrapServer string) *kafka.ImageKafkaProducer {
	imageKafkaProducer := kafka.NewImageProducerImpl(bootstrapServer)
	return imageKafkaProducer
}

// wire.go:

var (
	setKafkaProducerDependency = wire.NewSet(kafka.NewImageProducerImpl, wire.Bind(new(events.EventProducer), new(*kafka.ImageKafkaProducer)))

	setRedisRepositoryDependency = wire.NewSet(cache.NewImageRedisBRepositoryImpl, wire.Bind(new(repositories.ImageCacheRepository), new(*cache.ImageRedisBRepositoryImpl)))

	setMongoDBRepositoryDependency = wire.NewSet(persistence.NewImageMongoDBRepositoryImpl, wire.Bind(new(repositories.ImageNoSQLRepository), new(*persistence.ImageMongoDBRepositoryImpl)))

	setS3Dependency = wire.NewSet(s3storage.NewS3StorageImpl, wire.Bind(new(storage.Storage), new(*s3storage.S3StorageImpl)))
)
